  
    
language: android
jdk: oraclejdk8
# Turn off caching to avoid any caching problems
cache: false
# Don't use the Travis Container-Based Infrastructure - See #476
sudo: true
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default - see #247)

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"

# Only run tests on the main two OneBusAway brand flavors and the YRT Google flavor
script:
- ./gradlew assembleObaGoogleDebug assembleObaAmazonDebug assembleYrtGoogleDebug -PdisablePreDex
   
   
