language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    before_install:
    - yes | sdkmanager "platforms;android-28"
before_script:
 - chmod +x gradlew
 script:
  - ./gradlew assembleDebug --stacktrace
